#!/usr/bin/env bash
# 2-show_your_bash_pid.sh: This script displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.
# shellcheck disable=SC2009
ps auxf | grep "bash"
