#!/usr/bin/env bash
# This script is solving FizzBuzz 

# Loop from 1 to 100
for ((i = 1; i <= 100; i++))
do
    # Check if the number is a multiple of both 3 and 5 (i.e., divisible by 15)
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    # Check if the number is a multiple of 3 (but not 5)
    elif ((i % 3 == 0)); then
        echo "Fizz"
    # Check if the number is a multiple of 5 (but not 3)
    elif ((i % 5 == 0)); then
        echo "Buzz"
    # Otherwise, just display the number
    else
        echo "$i"
    fi
done
